.catalog:
  name: Kafka
  version: 0.10.2.1-rancher2
  description: |
    (Experimental) Apache Kafka cluster - JEFFK.
  minimum_rancher_version: v1.5.1
  maintainer: "Jeff Kolb <jeff.kolb@intlfcstone.com>"
  uuid: kafka-0
  questions:
    - variable: "kafka_scale"
      description: "Number of brokers nodes. Note: Recommended an odd number"
      label: "Broker Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "kafka_mem"
      description: "Amount of memory to config brokers."
      label: "Broker Memory (mb):"
      required: true
      default: 1024 
      type: "string"
    - variable: "kafka_log_dir"
      description: "Broker volume to log data"
      label: "Broker log volume:"
      required: true
      default: "/opt/kafka/logs"
      type: "string"
    - variable: "kafka_log_retention"
      description: "Broker log retention in hours"
      label: "Broker log retention (h):"
      required: true
      default: "168"
      type: "int"
    - variable: "kafka_num_partitions"
      description: "Number of broker partitions"
      label: "Broker partitions:"
      required: true
      default: "1"
      type: "int"
    - variable: "kafka_delete_topics"
      label: "Kafka delete topics:"
      description: |
        Enable delete topics in kafka.
      default: false
      required: true
      type: enum
      options:
        - false
        - true
    - variable: "kafka_interval"
      description: "Interval to poll/apply configuration changes. 0 to disable" 
      label: "Broker Interval (s):"
      required: true
      default: 60 
      type: "int"
    - variable: "kafka_pub_ip"
      description: "Advertise local and host public ip" 
      label: "Broker public ip:"
      default: false
      required: true
      type: enum
      options:
        - false
        - true
    - variable: "enable_jmx"
      description: "Enable JMX" 
      label: "Enable JMX on the appropriate interface"
      default: false
      required: true
      type: enum
      options:
        - false
        - true  
    - variable: "jmx_port"
      description: |
        This must be set if you would like to connect JMX agents to brokers
        If you set this, it will be exposed on broker containers (ex. 9999:9999).
      label: "JMX Port:"
      required: false
      default: ""
      type: "string"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use. 
        It's really recommended a dedicated zookeeper service just for Kafka.
      label: "Zookeeper stack/service"
      default: "kafka-zk/zk"
      required: true
      type: "service"
    - variable: "app_secret"
      description: "Application secret"
      label: "Application secret"
      required: true
      default: "letmein"
      type: "string"
    - variable: "km_args"
      description: "JVM arguments - Do not change this unless you know what you are doing!"
      label: "JVM arguments:"
      required: false
      default: "-Djava.net.preferIPv4Stack=true"
      type: "string"
    - variable: "volume_driver"
      description: "Volume driver to use for the Kafka Broker volume."
      label: "Driver:"
      required: true
      default: "local"
      type: "enum"
      options:
        - local
        - rancher-nfs

broker:
  scale: ${kafka_scale}
  retain_ip: true
  health_check:
    port: 9092
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
kafka-manager:
  scale: 1
  retain_ip: true
  health_check:
    port: 9000
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2


